### ISSUE TITLE
Modbus communication stops if a read holding register request times out

### ISSUE THREAD

**Issue by hmsjgr** [tyrrellsystems/node-red-contrib-serial-modbus#13]
Hi,

When I used these nodes to communicate with a Modbus sensor the Modbus communication stops working (both read and write nodes) if a read request e.g. times out (only tested read holding register). It seems like the node tries to process the data even if there is not data. When an error occurs the data variable is undefined.

Attached a patch with a solution that solves this issue. I'm not sure if it is the best one though.

[0001-Do-not-process-data-when-Modbus-request-fails.patch.zip](https://github.com/tyrrellsystems/node-red-contrib-serial-modbus/files/594649/0001-Do-not-process-data-when-Modbus-request-fails.patch.zip)

Best regards,
Jonas.

**Comment by hardillb** [comment]
Thanks, for spotting this.

Any chance you can submit the patch as a proper github pull request then it can be reviewed properly and then merged.

**Comment by hmsjgr** [comment]
Yes, of course!

**Comment by hardillb** [comment]
I've just published version 0.0.9 which should include this patch. Thanks
