### ISSUE TITLE
issues on Raspi with Serialport

### ISSUE THREAD

**Issue by creativeng** [tyrrellsystems/node-red-contrib-serial-modbus#18]
Hi Ben,

We have problems on running the package on RPI3, it seems there is a dependency with Serialport that cannot be resolved.
Are you aware about any problem like this?
Thanks

M

**Comment by hardillb** [comment]
No, you'll have to supply a fair bit more information about the failure

**Comment by creativeng** [comment]
This is the error..

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v46-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp)

**Comment by hardillb** [comment]
Show the WHOLE output, because that just means that there is no prebuilt binary for the platform and npm will normally build from source next

**Comment by hardillb** [comment]
also read #12

**Comment by creativeng** [comment]
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v46-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/usr/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/usr/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/build'
/usr/bin/node-red -> /usr/lib/node_modules/node-red/red.js
/usr/bin/node-red-pi -> /usr/lib/node_modules/node-red/bin/node-red-pi

**Comment by creativeng** [comment]
yet it seems so....
we will recheck full serial functionalities

**Comment by hardillb** [comment]
Right, so that looks like it's installed just fine

**Comment by creativeng** [comment]
ok 
ill let you know if everything ok....

**Comment by creativeng** [comment]
Hi Ben,
package working fine, also tested serial modbus..
thx
M

**Comment by creativeng** [comment]
i think it is a problem with Pi 3 to get the correct version of Nodejs...
