### ISSUE TITLE
wrting values

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-serial-modbus#19]
I am trying to use the write serial Modbus, however I am having some difficulties.  Tried the binary module mentioned in the readme text and have configured it as l32f (little endian 32 bit float) so when I try to inject a number of 140000 it brings back an error saying that error: invalid input.

Also there is only the option to write to one register, however if I  use the buffer from above it will need to use two, is this done automatically when using the right buffer size?

**Comment by hardillb** [comment]
As stated in the README.md the output node takes an offset to write the content of the buffer to, if it is bigger than one register/coil it will continue to the next one.

No idea about the first bit, there is no where near enough information to work out what's wrong

**Comment by davidoc85** [comment]
![image](https://cloud.githubusercontent.com/assets/22911216/21716877/5cf66648-d405-11e6-80ce-4d719a3696aa.png)

`[{"id":"8db6456e.daa0a8","type":"binary","z":"fde81681.5dd9e","name":"","pattern":"b32f => temp","x":532,"y":572,"wires":[["9e8931d1.687a7"]]},{"id":"9e8931d1.687a7","type":"debug","z":"fde81681.5dd9e","name":"","active":true,"console":"false","complete":"false","x":694,"y":572,"wires":[]},{"id":"251d2940.0d966e","type":"inject","z":"fde81681.5dd9e","name":"simple sensor object","topic":"","payload":"{\"temp\": 22.5}","payloadType":"json","repeat":"","crontab":"","once":false,"x":292,"y":572,"wires":[["8db6456e.daa0a8"]]},{"id":"71217299.b481dc","type":"comment","z":"fde81681.5dd9e","name":"build buffer from msg properties","info":"","x":333,"y":529,"wires":[]}]`

**Comment by davidoc85** [comment]
I solved the value type, as it appears it needs to have a property like in the example above
